// Generated by Aura Compiler (Target: ES6 / ECMAScript 2015+)
// Pragmatic Functional Programming for the Modern Web

// --- Dynamic Import Shim for Bundler Compatibility (Vite, Webpack, Rollup) ---
const __aura_import = (m) => import(/* @vite-ignore */ /* webpackIgnore: true */ m);

// --- Node.js Standard Library Integrations ---
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import osMod from "node:os";

// --- Backend Go-Style OS & Time Runtime ---
export const os = Object.freeze({
  args: typeof process !== 'undefined' ? process.argv.slice(2) : [],
  env: (k) => typeof process !== 'undefined' ? (process.env[k] || '') : '',
  getEnv: (k) => typeof process !== 'undefined' ? (process.env[k] || '') : '',
  setEnv: (k, v) => { if (typeof process !== 'undefined') process.env[k] = v; },
  exit: (code) => { if (typeof process !== 'undefined') process.exit(code); },
  readFile: (file) => fs.readFileSync(file, 'utf8'),
  writeFile: (file, data) => fs.writeFileSync(file, data, 'utf8'),
  hostname: () => { try { return osMod.hostname(); } catch (_) { return 'localhost'; } },
});

export const time = Object.freeze({
  now: () => Date.now(),
  sleep: (ms) => new Promise(res => setTimeout(res, ms)),
});

// --- Aura Standard Functional Primitives ---
export const None = Object.freeze({ $: "None" });
export const Some = (val) => Object.freeze({ $: "Some", _0: val });
export const Ok = (val) => Object.freeze({ $: "Ok", value: val });
export const Err = (err) => Object.freeze({ $: "Err", error: err });
export const __aura_unwrap = (v) => {
  if (v && typeof v === "object") {
    if (v.$ === "Err" || v.$ === "None") {
      throw { __aura_early_return: true, value: v };
    }
    if (v.$ === "Some") return v._0;
    if (v.$ === "Ok") return v.value;
  }
  return v;
};
if (typeof Map !== "undefined" && !Map.new) { Map.new = () => new Map(); }
if (typeof Set !== "undefined" && !Set.new) { Set.new = () => new Set(); }

// --- Aura Standard Functional Collections & Iterator Runtime ---
export class AuraIterator {
  constructor(iter) {
    if (typeof iter.next === "function") {
      this._iter = iter;
    } else if (typeof iter[Symbol.iterator] === "function") {
      this._iter = iter[Symbol.iterator]();
    } else {
      throw new TypeError("Value is not iterable");
    }
  }
  next() {
    const res = this._iter.next();
    if (!res || res.$ === "None" || res.done) return None;
    const val = res.$ === "Some" ? res._0 : (res.value !== undefined ? res.value : res);
    return Some(val);
  }
  map(fn) {
    const self = this;
    return new AuraIterator({
      next() {
        const res = self.next();
        if (res.$ === "None") return None;
        return Some(fn(res._0));
      }
    });
  }
  filter(pred) {
    const self = this;
    return new AuraIterator({
      next() {
        while (true) {
          const res = self.next();
          if (res.$ === "None") return None;
          if (pred(res._0)) return res;
        }
      }
    });
  }
  sort(cmp) {
    const defaultCmp = (a, b) => (typeof a === "number" && typeof b === "number" ? a - b : (a < b ? -1 : a > b ? 1 : 0));
    const effectiveCmp = cmp || defaultCmp;
    const items = this.toList();
    items.sort(effectiveCmp);
    let idx = 0;
    return new AuraIterator({
      next() {
        if (idx < items.length) {
          return Some(items[idx++]);
        }
        return None;
      }
    });
  }
  toList() {
    const out = [];
    while (true) {
      const res = this.next();
      if (res.$ === "None") break;
      out.push(res._0);
    }
    return out;
  }
  toArray() {
    return this.toList();
  }
  [Symbol.iterator]() {
    const self = this;
    return {
      next() {
        const res = self.next();
        if (res.$ === "None") return { done: true, value: undefined };
        return { done: false, value: res._0 };
      }
    };
  }
}
export const iter = (coll) => {
  if (coll instanceof AuraIterator) return coll;
  if (Array.isArray(coll)) {
    let idx = 0;
    return new AuraIterator({
      next() {
        if (idx < coll.length) return Some(coll[idx++]);
        return None;
      }
    });
  }
  return new AuraIterator(coll);
};
export const __aura_is_iter = (val) => {
  return val != null && typeof val !== "string" && !Array.isArray(val) && (typeof val.next === "function" || typeof val[Symbol.iterator] === "function");
};
export const __aura_iter = (coll) => {
  if (Array.isArray(coll) || typeof coll === "string") return coll;
  if (coll && (typeof coll[Symbol.iterator] === "function" || typeof coll[Symbol.asyncIterator] === "function")) return coll;
  if (coll && typeof coll.next === "function") return iter(coll);
  return coll;
};
export const map = (coll, fn) => {
  if (Array.isArray(coll)) return coll.map(fn);
  if (__aura_is_iter(coll)) return iter(coll).map(fn);
  if (coll && typeof coll.map === "function") return coll.map(fn);
  throw new TypeError("map called on non-collection");
};
export const filter = (coll, pred) => {
  if (Array.isArray(coll)) return coll.filter(pred);
  if (__aura_is_iter(coll)) return iter(coll).filter(pred);
  if (coll && typeof coll.filter === "function") return coll.filter(pred);
  throw new TypeError("filter called on non-collection");
};
export const sort = (coll, cmp) => {
  const defaultCmp = (a, b) => (typeof a === "number" && typeof b === "number" ? a - b : (a < b ? -1 : a > b ? 1 : 0));
  const effectiveCmp = cmp || defaultCmp;
  if (Array.isArray(coll)) return [...coll].sort(effectiveCmp);
  if (__aura_is_iter(coll)) return iter(coll).sort(cmp);
  if (coll && typeof coll.sort === "function") return coll.sort(cmp);
  throw new TypeError("sort called on non-collection");
};
export const toList = (coll) => {
  if (Array.isArray(coll)) return [...coll];
  if (coll && typeof coll.toList === "function") return coll.toList();
  return iter(coll).toList();
};
export const toArray = (coll) => toList(coll);

// --- Aura Concurrency (CSP) Runtime ---
export class Channel {
  constructor(capacity = 0) {
    this.capacity = capacity;
    this.buffer = [];
    this.sendQueue = [];
    this.recvQueue = [];
    this.closed = false;
  }
  static make(capacity = 0) {
    return new Channel(capacity);
  }
  static new(capacity = 0) {
    return new Channel(capacity);
  }
  static close(ch) {
    if (ch && ch.close) ch.close();
  }
  close() {
    if (this.closed) return;
    this.closed = true;
    while (this.recvQueue.length > 0) {
      const resolve = this.recvQueue.shift();
      resolve(None);
    }
    while (this.sendQueue.length > 0) {
      const { resolve } = this.sendQueue.shift();
      resolve(false);
    }
  }
  async send(value) {
    if (this.closed) throw new Error("Cannot send on closed channel");
    if (this.recvQueue.length > 0) {
      const resolve = this.recvQueue.shift();
      resolve(Some(value));
      return true;
    }
    if (this.capacity > 0 && this.buffer.length < this.capacity) {
      this.buffer.push(value);
      return true;
    }
    return new Promise((resolve) => {
      this.sendQueue.push({ value, resolve });
    });
  }
  async recv() {
    if (this.buffer.length > 0) {
      const val = this.buffer.shift();
      if (this.sendQueue.length > 0) {
        const { value, resolve } = this.sendQueue.shift();
        this.buffer.push(value);
        resolve(true);
      }
      return Some(val);
    }
    if (this.sendQueue.length > 0) {
      const { value, resolve } = this.sendQueue.shift();
      resolve(true);
      return Some(value);
    }
    if (this.closed) {
      return None;
    }
    return new Promise((resolve) => {
      this.recvQueue.push(resolve);
    });
  }
  async *[Symbol.asyncIterator]() {
    while (true) {
      const msg = await this.recv();
      if (!msg || msg.$ === "None") break;
      yield (msg._0 !== undefined ? msg._0 : msg.value);
    }
  }
}

export class WaitGroup {
  constructor() {
    this.counter = 0;
    this.waiters = [];
  }
  static new() {
    return new WaitGroup();
  }
  add(n = 1) {
    this.counter += n;
  }
  done() {
    this.counter = Math.max(0, this.counter - 1);
    if (this.counter === 0) {
      while (this.waiters.length > 0) {
        const resolve = this.waiters.shift();
        resolve();
      }
    }
  }
  async wait() {
    if (this.counter === 0) return;
    return new Promise((resolve) => {
      this.waiters.push(resolve);
    });
  }
}

export class Context {
  constructor(parent = null) {
    this.parent = parent;
    this._doneCh = Channel.make(1);
    this._err = null;
    this._values = new Map();
    this._isDone = false;
    this._timer = null;
    if (parent) {
      if (parent.isDone()) {
        this._cancel(parent._err || "context canceled");
      } else {
        spawn(async () => {
          await parent.done().recv();
          if (!this._isDone) {
            this._cancel(parent._err || "context canceled");
          }
        });
      }
    }
  }
  static background() {
    return new Context();
  }
  static todo() {
    return new Context();
  }
  static withCancel(parent) {
    const ctx = new Context(parent);
    const cancel = (reason = "context canceled") => {
      ctx._cancel(reason);
    };
    return [ctx, cancel];
  }
  static withTimeout(parent, ms) {
    const ctx = new Context(parent);
    const cancel = (reason = "context canceled") => {
      if (ctx._timer) clearTimeout(ctx._timer);
      ctx._cancel(reason);
    };
    ctx._timer = setTimeout(() => {
      ctx._cancel("context deadline exceeded");
    }, ms);
    return [ctx, cancel];
  }
  static withValue(parent, key, value) {
    const ctx = new Context(parent);
    ctx._values.set(key, value);
    return ctx;
  }
  _cancel(reason = "context canceled") {
    if (this._isDone) return;
    this._isDone = true;
    if (this._timer) clearTimeout(this._timer);
    this._err = (typeof reason === "string" ? reason : "context canceled");
    this._doneCh.close();
  }
  done() {
    return this._doneCh;
  }
  err() {
    return this._err ? Some(this._err) : None;
  }
  isDone() {
    return this._isDone;
  }
  value(key) {
    if (this._values.has(key)) {
      return Some(this._values.get(key));
    }
    if (this.parent) {
      return this.parent.value(key);
    }
    return None;
  }
}

export const spawn = (task) => {
  if (typeof task === "function") {
    Promise.resolve().then(() => task()).catch(console.error);
  } else {
    Promise.resolve(task).catch(console.error);
  }
};
export class Pointer {
  constructor(getOrVal, set) {
    if (typeof getOrVal === "function" && typeof set === "function") {
      this._get = getOrVal;
      this._set = set;
    } else {
      this._val = getOrVal;
      this._get = () => this._val;
      this._set = (v) => { this._val = v; };
    }
  }
  get value() { return this._get(); }
  set value(v) { this._set(v); }
  get val() { return this._get(); }
  set val(v) { this._set(v); }
}
export function ptr(val) {
  return new Pointer(val);
}

export class AuraPanic extends Error {
  constructor(value) {
    super(typeof value === "string" ? value : JSON.stringify(value));
    this.value = value;
    this.isPanic = true;
  }
}
let __current_panic = null;
export function panic(value) {
  throw new AuraPanic(value);
}
export function recover() {
  if (__current_panic !== null) {
    const v = __current_panic;
    __current_panic = null;
    return Some(v);
  }
  return None;
}

export class Mutex {
  constructor() {
    this._locked = false;
    this._waiters = [];
  }
  static new() { return new Mutex(); }
  async lock() {
    if (!this._locked) {
      this._locked = true;
      return;
    }
    return new Promise(resolve => this._waiters.push(resolve));
  }
  unlock() {
    if (this._waiters.length > 0) {
      const next = this._waiters.shift();
      next();
    } else {
      this._locked = false;
    }
  }
  tryLock() {
    if (!this._locked) {
      this._locked = true;
      return true;
    }
    return false;
  }
}

export class RWMutex {
  constructor() {
    this._readers = 0;
    this._writing = false;
    this._writeWaiters = [];
    this._readWaiters = [];
  }
  static new() { return new RWMutex(); }
  async lock() {
    if (!this._writing && this._readers === 0) {
      this._writing = true;
      return;
    }
    return new Promise(resolve => this._writeWaiters.push(resolve));
  }
  unlock() {
    this._writing = false;
    if (this._readWaiters.length > 0) {
      while (this._readWaiters.length > 0) {
        this._readers++;
        const r = this._readWaiters.shift();
        r();
      }
    } else if (this._writeWaiters.length > 0) {
      this._writing = true;
      const w = this._writeWaiters.shift();
      w();
    }
  }
  async rLock() {
    if (!this._writing && this._writeWaiters.length === 0) {
      this._readers++;
      return;
    }
    return new Promise(resolve => this._readWaiters.push(resolve));
  }
  rUnlock() {
    this._readers = Math.max(0, this._readers - 1);
    if (this._readers === 0 && this._writeWaiters.length > 0) {
      this._writing = true;
      const w = this._writeWaiters.shift();
      w();
    }
  }
}

export class Once {
  constructor() {
    this._done = false;
  }
  static new() { return new Once(); }
  do(fn) {
    if (!this._done) {
      this._done = true;
      fn();
    }
  }
}

export class Pool {
  constructor(newFn = null) {
    this._newFn = newFn;
    this._items = [];
  }
  static new(newFn = null) { return new Pool(newFn); }
  get() {
    if (this._items.length > 0) {
      return this._items.pop();
    }
    if (typeof this._newFn === "function") {
      return this._newFn();
    }
    return null;
  }
  put(item) {
    this._items.push(item);
  }
}

export const Sync = {
  Mutex,
  RWMutex,
  Once,
  Pool,
  WaitGroup,
};

export const close = (ch) => Channel.close(ch);
export const StructTag = {
  get: (target, field, tagKey) => {
    if (!target) return None;
    const tags = target.__tags || (target.constructor && target.constructor.__tags);
    if (tags && tags[field] && tags[field][tagKey] !== undefined) {
      return Some(tags[field][tagKey]);
    }
    return None;
  }
};

export const int8 = (v) => (v << 24) >> 24;
export const int16 = (v) => (v << 16) >> 16;
export const int32 = (v) => v | 0;
export const int64 = (v) => typeof v === "bigint" ? BigInt.asIntN(64, v) : BigInt(v);
export const uint8 = (v) => v & 0xFF;
export const uint16 = (v) => v & 0xFFFF;
export const uint32 = (v) => v >>> 0;
export const uint64 = (v) => typeof v === "bigint" ? BigInt.asUintN(64, v) : BigInt(v);
export const float32 = (v) => Math.fround(v);
export const float64 = (v) => Number(v);
export const byte = (v) => v & 0xFF;
export const rune = (v) => v | 0;

export const timeout = (ms) => new Promise(resolve => setTimeout(resolve, ms));
export const sleep = timeout;
export const print = (...args) => console.log(...args);
export const println = (...args) => console.log(...args);

// --- Aura Standard Testing & Assertion Primitives ---
export function __aura_deep_equal(a, b) {
  if (a === b) return true;
  if (a == null || b == null) return false;
  if (typeof a !== "object" || typeof b !== "object") return false;
  if (Array.isArray(a) !== Array.isArray(b)) return false;
  if (Array.isArray(a)) {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) {
      if (!__aura_deep_equal(a[i], b[i])) return false;
    }
    return true;
  }
  const keysA = Object.keys(a);
  const keysB = Object.keys(b);
  if (keysA.length !== keysB.length) return false;
  for (const k of keysA) {
    if (!Object.prototype.hasOwnProperty.call(b, k)) return false;
    if (!__aura_deep_equal(a[k], b[k])) return false;
  }
  return true;
}
export const assert = (condition, message = "Assertion failed") => {
  if (!condition) throw new Error(typeof message === "string" ? message : JSON.stringify(message));
};
export const assertTrue = (condition, message = "Expected true") => {
  if (condition !== true) throw new Error(`${message}: received ${JSON.stringify(condition)}`);
};
export const assertFalse = (condition, message = "Expected false") => {
  if (condition !== false) throw new Error(`${message}: received ${JSON.stringify(condition)}`);
};
export const assertEqual = (actual, expected, message) => {
  if (!__aura_deep_equal(actual, expected)) {
    const msg = message ? `${message} - ` : "";
    throw new Error(`${msg}Expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
};
export const assertNotEqual = (actual, expected, message) => {
  if (__aura_deep_equal(actual, expected)) {
    const msg = message ? `${message} - ` : "";
    throw new Error(`${msg}Expected values to be different, but both were ${JSON.stringify(actual)}`);
  }
};
export const assertDeepEqual = assertEqual;
export const assertThrows = (fn, expected) => {
  let threw = false;
  let caught = null;
  try { fn(); } catch (err) { threw = true; caught = err; }
  if (!threw) throw new Error("Expected function to throw an error, but it did not.");
  if (expected && !String(caught).includes(String(expected))) {
    throw new Error(`Expected error containing '${expected}', got '${caught}'`);
  }
};

export const __aura_select = async (cases, defaultFn = null) => {
  const readyIndices = [];
  for (let i = 0; i < cases.length; i++) {
    const c = cases[i];
    if (c.kind === "recv") {
      if (c.channel.buffer.length > 0 || c.channel.sendQueue.length > 0 || c.channel.closed) {
        readyIndices.push(i);
      }
    } else if (c.kind === "send") {
      if (c.channel.recvQueue.length > 0 || (c.channel.capacity > 0 && c.channel.buffer.length < c.channel.capacity)) {
        readyIndices.push(i);
      }
    }
  }
  if (readyIndices.length > 0) {
    const chosenIdx = readyIndices[Math.floor(Math.random() * readyIndices.length)];
    const chosen = cases[chosenIdx];
    if (chosen.kind === "recv") {
      const msg = await chosen.channel.recv();
      return await chosen.fn(msg);
    } else if (chosen.kind === "send") {
      await chosen.channel.send(chosen.value);
      return await chosen.fn();
    }
  }
  if (defaultFn) {
    return await defaultFn();
  }
  const promises = cases.map((c, idx) => {
    if (c.kind === "recv") {
      return c.channel.recv().then(msg => ({ idx, val: msg }));
    } else if (c.kind === "send") {
      return c.channel.send(c.value).then(() => ({ idx, val: undefined }));
    } else if (c.kind === "timeout") {
      return (typeof c.ms === "number" ? timeout(c.ms) : Promise.resolve(c.ms)).then(() => ({ idx, val: undefined }));
    }
    return Promise.reject("Invalid select case");
  });
  const winner = await Promise.race(promises);
  const targetCase = cases[winner.idx];
  return await targetCase.fn(winner.val);
};

// --- Aura Standard HTTP Server (Golang Style) ---
class __AuraServeMux {
  constructor() {
    this.routes = [];
    this.middlewares = [];
    this.server = null;
  }
  use(middleware) {
    this.middlewares.push(middleware);
    return this;
  }
  handle(pattern, handler) {
    this._addRoute(null, pattern, handler);
    return this;
  }
  handleFunc(pattern, handler) {
    this._addRoute(null, pattern, handler);
    return this;
  }
  get(pattern, handler) {
    this._addRoute('GET', pattern, handler);
    return this;
  }
  post(pattern, handler) {
    this._addRoute('POST', pattern, handler);
    return this;
  }
  put(pattern, handler) {
    this._addRoute('PUT', pattern, handler);
    return this;
  }
  delete(pattern, handler) {
    this._addRoute('DELETE', pattern, handler);
    return this;
  }
  patch(pattern, handler) {
    this._addRoute('PATCH', pattern, handler);
    return this;
  }
  _addRoute(method, pattern, handler) {
    const paramNames = [];
    let regexStr = "^";
    let isPrefix = false;
    let effMethod = method;
    let effPattern = (pattern || '/').trim();
    if (!effMethod && effPattern.includes(' ')) {
      const parts = effPattern.split(/\s+/, 2);
      effMethod = parts[0].toUpperCase();
      effPattern = parts[1];
    }
    const segments = effPattern.split('/').filter(Boolean);
    if (segments.length === 0) {
      regexStr = '^\\/?$';
    } else {
      for (let i = 0; i < segments.length; i++) {
        const seg = segments[i];
        if (seg === '*') {
          regexStr += '(?:\\/.*)?$';
          isPrefix = true;
          break;
        } else if (seg.startsWith(':') || (seg.startsWith('{') && seg.endsWith('}'))) {
          const name = seg.startsWith(':') ? seg.slice(1) : seg.slice(1, -1);
          paramNames.push(name);
          regexStr += '\\/([^\\/]+)';
        } else {
          regexStr += '\\/' + seg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        }
      }
      if (!isPrefix) {
        regexStr += '\\/?$';
      }
    }
    this.routes.push({
      method: effMethod ? effMethod.toUpperCase() : null,
      pattern: effPattern,
      regex: new RegExp(regexStr),
      paramNames,
      handler
    });
  }
  async serveHTTP(req, res) {
    const url = new URL(req.url || '/', `http://${req.headers?.host || 'localhost'}`);
    req.urlParsed = url;
    req.query = Object.fromEntries(url.searchParams.entries());
    req.params = {};
    let matched = null;
    for (const route of this.routes) {
      if (route.method && route.method !== req.method) continue;
      const match = url.pathname.match(route.regex);
      if (match) {
        matched = { route, match };
        break;
      }
    }
    if (!matched) {
      const pathMatched = this.routes.some(r => url.pathname.match(r.regex));
      if (pathMatched) {
        res.writeHead(405, { 'Content-Type': 'text/plain; charset=utf-8' });
        res.end('405 Method Not Allowed');
        return;
      }
      res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('404 Not Found');
      return;
    }
    const { route, match } = matched;
    route.paramNames.forEach((name, idx) => {
      req.params[name] = decodeURIComponent(match[idx + 1] || '');
    });
    let index = 0;
    const allHandlers = [...this.middlewares, async (q, s) => {
      if (typeof route.handler === 'function') {
        return await route.handler(q, s);
      } else if (route.handler && typeof route.handler.serveHTTP === 'function') {
        return await route.handler.serveHTTP(q, s);
      }
    }];
    const next = async () => {
      if (index < allHandlers.length) {
        const fn = allHandlers[index++];
        if (fn.length >= 3) {
          return await fn(req, res, next);
        } else {
          await fn(req, res);
          return await next();
        }
      }
    };
    try {
      await next();
    } catch (err) {
      if (!res.headersSent) {
        res.writeHead(500, { 'Content-Type': 'text/plain; charset=utf-8' });
        res.end(`Internal Server Error: ${err?.message || err}`);
      }
    }
  }
  async listenAndServe(addr) {
    const parts = (addr || ':8080').split(':');
    const port = parseInt(parts[parts.length - 1], 10) || 8080;
    const host = parts.length > 1 && parts[0] ? parts[0] : '0.0.0.0';
    const node_http = await __aura_import('node:http');
    const server = (node_http.createServer || node_http.default?.createServer || node_http)((req, res) => this.serveHTTP(req, res));
    this.server = server;
    return new Promise((resolve, reject) => {
      server.listen(port, host, () => resolve(server));
      server.on('error', reject);
    });
  }
  close() {
    return new Promise((resolve, reject) => {
      if (this.server) {
        this.server.close((err) => err ? reject(err) : resolve());
      } else {
        resolve();
      }
    });
  }
}
const __defaultMux = new __AuraServeMux();
export const http = {
  StatusOK: 200,
  StatusCreated: 201,
  StatusAccepted: 202,
  StatusNoContent: 204,
  StatusMovedPermanently: 301,
  StatusFound: 302,
  StatusBadRequest: 400,
  StatusUnauthorized: 401,
  StatusForbidden: 403,
  StatusNotFound: 404,
  StatusMethodNotAllowed: 405,
  StatusConflict: 409,
  StatusUnprocessableEntity: 422,
  StatusInternalServerError: 500,
  StatusBadGateway: 502,
  StatusServiceUnavailable: 503,
  newServeMux: () => new __AuraServeMux(),
  NewServeMux: () => new __AuraServeMux(),
  handleFunc: (path, handler) => __defaultMux.handleFunc(path, handler),
  handle: (path, handler) => __defaultMux.handle(path, handler),
  get: (path, handler) => __defaultMux.get(path, handler),
  post: (path, handler) => __defaultMux.post(path, handler),
  put: (path, handler) => __defaultMux.put(path, handler),
  delete: (path, handler) => __defaultMux.delete(path, handler),
  patch: (path, handler) => __defaultMux.patch(path, handler),
  use: (middleware) => __defaultMux.use(middleware),
  listenAndServe: (addr) => __defaultMux.listenAndServe(addr),
  serveHTTP: (req, res) => __defaultMux.serveHTTP(req, res),
  close: () => __defaultMux.close(),
  json: (res, statusCode, data) => {
    const payload = JSON.stringify(data);
    res.writeHead(statusCode, {
      'Content-Type': 'application/json; charset=utf-8',
      'Content-Length': Buffer.byteLength(payload)
    });
    res.end(payload);
  },
  text: (res, statusCode, message) => {
    const payload = String(message ?? '');
    res.writeHead(statusCode, {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Length': Buffer.byteLength(payload)
    });
    res.end(payload);
  },
  html: (res, statusCode, htmlContent) => {
    const payload = String(htmlContent ?? '');
    res.writeHead(statusCode, {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Length': Buffer.byteLength(payload)
    });
    res.end(payload);
  },
  error: (res, errorMsg, statusCode = 500) => {
    const payload = String(errorMsg ?? 'Internal Server Error');
    res.writeHead(statusCode, {
      'Content-Type': 'text/plain; charset=utf-8',
      'Content-Length': Buffer.byteLength(payload)
    });
    res.end(payload);
  },
  redirect: (res, url, statusCode = 302) => {
    res.writeHead(statusCode, { 'Location': url });
    res.end();
  },
  pathValue: (req, paramName) => {
    return (req && req.params && req.params[paramName]) || '';
  },
  query: (req, queryName) => {
    if (req && req.urlParsed && req.urlParsed.searchParams) {
      return req.urlParsed.searchParams.get(queryName) || '';
    }
    if (req && req.query && req.query[queryName]) {
      return req.query[queryName];
    }
    return '';
  },
  parseJson: (req) => {
    return new Promise((resolve) => {
      let body = '';
      req.on('data', chunk => { body += chunk; });
      req.on('end', () => {
        try {
          const parsed = body ? JSON.parse(body) : {};
          resolve(Ok(parsed));
        } catch (e) {
          resolve(Err(`Invalid JSON body: ${e.message}`));
        }
      });
      req.on('error', (err) => {
        resolve(Err(`Request error: ${err.message}`));
      });
    });
  },
  serveFile: (res, req, filePath) => {
    if (!fs.existsSync(filePath)) {
      res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('File Not Found');
      return;
    }
    const ext = path.extname(filePath).toLowerCase();
    const mimeTypes = {
      '.html': 'text/html; charset=utf-8',
      '.css': 'text/css; charset=utf-8',
      '.js': 'application/javascript; charset=utf-8',
      '.mjs': 'application/javascript; charset=utf-8',
      '.json': 'application/json; charset=utf-8',
      '.png': 'image/png',
      '.jpg': 'image/jpeg',
      '.jpeg': 'image/jpeg',
      '.gif': 'image/gif',
      '.svg': 'image/svg+xml',
      '.txt': 'text/plain; charset=utf-8'
    };
    const contentType = mimeTypes[ext] || 'application/octet-stream';
    const stat = fs.statSync(filePath);
    res.writeHead(200, {
      'Content-Type': contentType,
      'Content-Length': stat.size
    });
    const readStream = fs.createReadStream(filePath);
    readStream.pipe(res);
  },
  fileServer: (rootDir) => {
    return (req, res) => {
      const url = new URL(req.url || '/', `http://${req.headers?.host || 'localhost'}`);
      const safePath = path.normalize(url.pathname).replace(/^(\.\.[\/\\])+/, '');
      const filePath = path.join(rootDir, safePath === '/' ? 'index.html' : safePath);
      http.serveFile(res, req, filePath);
    };
  }
};

// --- Aura Standard MySQL Database Driver & Pool ---
const __createAuraMysqlWrapper = (driverOrConfig) => {
  let mysqlPkg = null;
  let poolInstance = null;
  const getDriver = async () => {
    if (!mysqlPkg) {
      try {
        mysqlPkg = await __aura_import('mysql2/promise');
      } catch (_) {
        try {
          mysqlPkg = await __aura_import('mysql2');
        } catch (err) {
          throw new Error('Aura MySQL runtime requires "mysql2" package. Run: npm install mysql2');
        }
      }
    }
    return mysqlPkg;
  };
  const getPool = async () => {
    if (!poolInstance) {
      const drv = await getDriver();
      const config = typeof driverOrConfig === 'string' ? { uri: driverOrConfig } : (driverOrConfig || {});
      poolInstance = (drv.createPool || drv.default?.createPool)(config);
    }
    return poolInstance;
  };
  return {
    query: async (sql, params = []) => {
      try {
        const pool = await getPool();
        const [rows] = await pool.query(sql, params);
        return Ok(Array.isArray(rows) ? rows : [rows]);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    execute: async (sql, params = []) => {
      try {
        const pool = await getPool();
        const [result] = await pool.execute(sql, params);
        return Ok({
          affectedRows: result.affectedRows || 0,
          insertId: result.insertId || 0,
          changedRows: result.changedRows || 0,
          warningCount: result.warningCount || 0
        });
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    queryRow: async (sql, params = []) => {
      try {
        const pool = await getPool();
        const [rows] = await pool.query(sql, params);
        if (Array.isArray(rows) && rows.length > 0) {
          return Ok(Some(rows[0]));
        } else {
          return Ok(None);
        }
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    transaction: async (callback) => {
      try {
        const pool = await getPool();
        const connection = await pool.getConnection();
        try {
          await connection.beginTransaction();
          const txWrapper = {
            query: async (sql, params = []) => {
              try {
                const [rows] = await connection.query(sql, params);
                return Ok(Array.isArray(rows) ? rows : [rows]);
              } catch (e) { return Err(e.message || String(e)); }
            },
            execute: async (sql, params = []) => {
              try {
                const [res] = await connection.execute(sql, params);
                return Ok({ affectedRows: res.affectedRows || 0, insertId: res.insertId || 0, changedRows: res.changedRows || 0, warningCount: res.warningCount || 0 });
              } catch (e) { return Err(e.message || String(e)); }
            },
            queryRow: async (sql, params = []) => {
              try {
                const [rows] = await connection.query(sql, params);
                return Ok(Array.isArray(rows) && rows.length > 0 ? Some(rows[0]) : None);
              } catch (e) { return Err(e.message || String(e)); }
            },
            commit: async () => {
              try { await connection.commit(); return Ok(undefined); } catch (e) { return Err(e.message || String(e)); }
            },
            rollback: async () => {
              try { await connection.rollback(); return Ok(undefined); } catch (e) { return Err(e.message || String(e)); }
            }
          };
          const result = await callback(txWrapper);
          await connection.commit();
          return Ok(result);
        } catch (txErr) {
          try { await connection.rollback(); } catch (_) {}
          return Err(txErr.message || String(txErr));
        } finally {
          connection.release();
        }
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    ping: async () => {
      try {
        const pool = await getPool();
        await pool.query('SELECT 1');
        return Ok(true);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    close: async () => {
      try {
        if (poolInstance) await poolInstance.end();
        return Ok(undefined);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    end: async () => {
      try {
        if (poolInstance) await poolInstance.end();
        return Ok(undefined);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    escape: (val) => {
      if (val === null || val === undefined) return 'NULL';
      if (typeof val === 'number') return String(val);
      if (typeof val === 'boolean') return val ? 'true' : 'false';
      return "'" + String(val).replace(/[\\\'\"\x00\n\r\x1a]/g, (s) => {
        switch (s) {
          case '\\': return '\\\\';
          case '\'': return '\\\'';
          case '"': return '\\"';
          case '\0': return '\\0';
          case '\n': return '\\n';
          case '\r': return '\\r';
          case '\x1a': return '\\Z';
          default: return '\\' + s;
        }
      }) + "'";
    },
    format: function(sql, params = []) {
      let idx = 0;
      return sql.replace(/\?/g, () => {
        if (idx < params.length) {
          return this.escape(params[idx++]);
        }
        return '?';
      });
    }
  };
};
export const mysql = {
  createPool: (config) => __createAuraMysqlWrapper(config),
  createConnection: (config) => __createAuraMysqlWrapper(config),
  open: (uri) => __createAuraMysqlWrapper(uri),
  escape: (val) => __createAuraMysqlWrapper().escape(val),
  format: (sql, params) => __createAuraMysqlWrapper().format(sql, params)
};

// --- Aura Standard PostgreSQL Database Driver & Pool ---
const __createAuraPgWrapper = (driverOrConfig) => {
  let pgPkg = null;
  let poolInstance = null;
  const getDriver = async () => {
    if (!pgPkg) {
      try {
        pgPkg = await __aura_import('pg');
      } catch (err) {
        throw new Error('Aura PostgreSQL runtime requires "pg" package. Run: npm install pg');
      }
    }
    return pgPkg;
  };
  const getPool = async () => {
    if (!poolInstance) {
      const drv = await getDriver();
      let poolConfig = {};
      if (typeof driverOrConfig === 'string') {
        poolConfig = { connectionString: driverOrConfig };
      } else if (driverOrConfig && typeof driverOrConfig === 'object') {
        poolConfig = { ...driverOrConfig };
        if (poolConfig.uri && !poolConfig.connectionString) poolConfig.connectionString = poolConfig.uri;
        if (poolConfig.connectionLimit && !poolConfig.max) poolConfig.max = poolConfig.connectionLimit;
      }
      const PoolClass = drv.Pool || drv.default?.Pool || drv.default;
      poolInstance = new PoolClass(poolConfig);
    }
    return poolInstance;
  };
  const normalizePgSql = (sql) => {
    if (typeof sql !== 'string') return sql;
    let count = 0;
    return sql.replace(/\?/g, () => '$' + (++count));
  };
  return {
    query: async (sql, params = []) => {
      try {
        const pool = await getPool();
        const res = await pool.query(normalizePgSql(sql), params);
        return Ok(Array.isArray(res.rows) ? res.rows : []);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    execute: async (sql, params = []) => {
      try {
        const pool = await getPool();
        const res = await pool.query(normalizePgSql(sql), params);
        let insertId = 0;
        if (res.rows && res.rows.length > 0 && res.rows[0].id !== undefined) {
          insertId = typeof res.rows[0].id === 'number' ? res.rows[0].id : Number(res.rows[0].id) || 0;
        }
        return Ok({
          rowCount: res.rowCount || 0,
          command: res.command || '',
          insertId: insertId,
          affectedRows: res.rowCount || 0
        });
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    queryRow: async (sql, params = []) => {
      try {
        const pool = await getPool();
        const res = await pool.query(normalizePgSql(sql), params);
        if (res.rows && res.rows.length > 0) {
          return Ok(Some(res.rows[0]));
        } else {
          return Ok(None);
        }
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    transaction: async (callback) => {
      try {
        const pool = await getPool();
        const client = await pool.connect();
        try {
          await client.query('BEGIN');
          const txWrapper = {
            query: async (sql, params = []) => {
              try {
                const res = await client.query(normalizePgSql(sql), params);
                return Ok(Array.isArray(res.rows) ? res.rows : []);
              } catch (e) { return Err(e.message || String(e)); }
            },
            execute: async (sql, params = []) => {
              try {
                const res = await client.query(normalizePgSql(sql), params);
                let insertId = 0;
                if (res.rows && res.rows.length > 0 && res.rows[0].id !== undefined) {
                  insertId = typeof res.rows[0].id === 'number' ? res.rows[0].id : Number(res.rows[0].id) || 0;
                }
                return Ok({
                  rowCount: res.rowCount || 0,
                  command: res.command || '',
                  insertId: insertId,
                  affectedRows: res.rowCount || 0
                });
              } catch (e) { return Err(e.message || String(e)); }
            },
            queryRow: async (sql, params = []) => {
              try {
                const res = await client.query(normalizePgSql(sql), params);
                return Ok(res.rows && res.rows.length > 0 ? Some(res.rows[0]) : None);
              } catch (e) { return Err(e.message || String(e)); }
            },
            commit: async () => {
              try { await client.query('COMMIT'); return Ok(undefined); } catch (e) { return Err(e.message || String(e)); }
            },
            rollback: async () => {
              try { await client.query('ROLLBACK'); return Ok(undefined); } catch (e) { return Err(e.message || String(e)); }
            }
          };
          const result = await callback(txWrapper);
          await client.query('COMMIT');
          return Ok(result);
        } catch (txErr) {
          try { await client.query('ROLLBACK'); } catch (_) {}
          return Err(txErr.message || String(txErr));
        } finally {
          client.release();
        }
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    ping: async () => {
      try {
        const pool = await getPool();
        await pool.query('SELECT 1');
        return Ok(true);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    close: async () => {
      try {
        if (poolInstance) await poolInstance.end();
        return Ok(undefined);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    end: async () => {
      try {
        if (poolInstance) await poolInstance.end();
        return Ok(undefined);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    escapeIdentifier: (id) => {
      return '"' + String(id).replace(/"/g, '""') + '"';
    },
    escapeLiteral: (val) => {
      if (val === null || val === undefined) return 'NULL';
      if (typeof val === 'number') return String(val);
      if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
      return "'" + String(val).replace(/'/g, "''") + "'";
    },
    escape: (val) => {
      if (val === null || val === undefined) return 'NULL';
      if (typeof val === 'number') return String(val);
      if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
      return "'" + String(val).replace(/'/g, "''") + "'";
    },
    format: function(sql, params = []) {
      let idx = 0;
      let formatted = sql.replace(/\$(\d+)/g, (match, num) => {
        const i = parseInt(num, 10) - 1;
        if (i >= 0 && i < params.length) {
          return this.escape(params[i]);
        }
        return match;
      });
      formatted = formatted.replace(/\?/g, () => {
        if (idx < params.length) {
          return this.escape(params[idx++]);
        }
        return '?';
      });
      return formatted;
    }
  };
};
export const postgres = {
  createPool: (config) => __createAuraPgWrapper(config),
  createClient: (config) => __createAuraPgWrapper(config),
  open: (uri) => __createAuraPgWrapper(uri),
  escapeIdentifier: (id) => __createAuraPgWrapper().escapeIdentifier(id),
  escapeLiteral: (val) => __createAuraPgWrapper().escapeLiteral(val),
  escape: (val) => __createAuraPgWrapper().escape(val),
  format: (sql, params) => __createAuraPgWrapper().format(sql, params)
};
export const pg = postgres;

// --- Aura Standard MongoDB Database Driver & Client ---
const __createAuraMongoWrapper = (driverOrConfig) => {
  let mongoPkg = null;
  let clientInstance = null;
  const getDriver = async () => {
    if (!mongoPkg) {
      try {
        mongoPkg = await __aura_import('mongodb');
      } catch (err) {
        throw new Error('Aura MongoDB runtime requires "mongodb" package. Run: npm install mongodb');
      }
    }
    return mongoPkg;
  };
  const getClient = async () => {
    if (!clientInstance) {
      const drv = await getDriver();
      const MongoClientClass = drv.MongoClient || drv.default?.MongoClient || drv.default;
      let uri = 'mongodb://localhost:27017';
      let options = {};
      if (typeof driverOrConfig === 'string') {
        uri = driverOrConfig;
      } else if (driverOrConfig && typeof driverOrConfig === 'object') {
        if (driverOrConfig.uri) {
          uri = driverOrConfig.uri;
        } else if (driverOrConfig.host) {
          const auth = driverOrConfig.user && driverOrConfig.password ? `${encodeURIComponent(driverOrConfig.user)}:${encodeURIComponent(driverOrConfig.password)}@` : '';
          const port = driverOrConfig.port ? `:${driverOrConfig.port}` : '';
          const db = driverOrConfig.database ? `/${driverOrConfig.database}` : '';
          uri = `mongodb://${auth}${driverOrConfig.host}${port}${db}`;
        }
        options = { ...driverOrConfig };
      }
      clientInstance = new MongoClientClass(uri, options);
      await clientInstance.connect();
    }
    return clientInstance;
  };
  const wrapCollection = (getColFn) => {
    return {
      find: async (filter = {}, options = {}) => {
        try {
          const col = await getColFn();
          const docs = await col.find(filter, options).toArray();
          return Ok(Array.isArray(docs) ? docs : []);
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      findOne: async (filter = {}, options = {}) => {
        try {
          const col = await getColFn();
          const doc = await col.findOne(filter, options);
          return Ok(doc ? Some(doc) : None);
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      insertOne: async (doc) => {
        try {
          const col = await getColFn();
          const res = await col.insertOne(doc);
          return Ok({
            insertedId: res.insertedId,
            acknowledged: !!res.acknowledged
          });
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      insertMany: async (docs) => {
        try {
          const col = await getColFn();
          const res = await col.insertMany(docs);
          const ids = res.insertedIds ? Object.values(res.insertedIds) : [];
          return Ok({
            insertedIds: ids,
            insertedCount: res.insertedCount || ids.length,
            acknowledged: !!res.acknowledged
          });
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      updateOne: async (filter, update, options = {}) => {
        try {
          const col = await getColFn();
          const res = await col.updateOne(filter, update, options);
          return Ok({
            matchedCount: res.matchedCount || 0,
            modifiedCount: res.modifiedCount || 0,
            upsertedId: res.upsertedId || null,
            acknowledged: !!res.acknowledged
          });
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      updateMany: async (filter, update, options = {}) => {
        try {
          const col = await getColFn();
          const res = await col.updateMany(filter, update, options);
          return Ok({
            matchedCount: res.matchedCount || 0,
            modifiedCount: res.modifiedCount || 0,
            upsertedId: res.upsertedId || null,
            acknowledged: !!res.acknowledged
          });
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      deleteOne: async (filter = {}) => {
        try {
          const col = await getColFn();
          const res = await col.deleteOne(filter);
          return Ok({
            deletedCount: res.deletedCount || 0,
            acknowledged: !!res.acknowledged
          });
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      deleteMany: async (filter = {}) => {
        try {
          const col = await getColFn();
          const res = await col.deleteMany(filter);
          return Ok({
            deletedCount: res.deletedCount || 0,
            acknowledged: !!res.acknowledged
          });
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      countDocuments: async (filter = {}) => {
        try {
          const col = await getColFn();
          const count = await col.countDocuments(filter);
          return Ok(count);
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      aggregate: async (pipeline = []) => {
        try {
          const col = await getColFn();
          const res = await col.aggregate(pipeline).toArray();
          return Ok(Array.isArray(res) ? res : []);
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      drop: async () => {
        try {
          const col = await getColFn();
          const res = await col.drop();
          return Ok(!!res);
        } catch (err) {
          return Err(err.message || String(err));
        }
      }
    };
  };
  const wrapDb = (getDbFn) => {
    return {
      collection: (name) => wrapCollection(async () => {
        const db = await getDbFn();
        return db.collection(name);
      }),
      listCollections: async () => {
        try {
          const db = await getDbFn();
          const cols = await db.listCollections().toArray();
          return Ok(cols);
        } catch (err) {
          return Err(err.message || String(err));
        }
      },
      dropDatabase: async () => {
        try {
          const db = await getDbFn();
          const res = await db.dropDatabase();
          return Ok(!!res);
        } catch (err) {
          return Err(err.message || String(err));
        }
      }
    };
  };
  return {
    db: (name) => wrapDb(async () => {
      const cli = await getClient();
      return cli.db(name);
    }),
    collection: (name) => wrapCollection(async () => {
      const cli = await getClient();
      return cli.db().collection(name);
    }),
    ping: async () => {
      try {
        const cli = await getClient();
        await cli.db('admin').command({ ping: 1 });
        return Ok(true);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    close: async () => {
      try {
        if (clientInstance) await clientInstance.close();
        return Ok(undefined);
      } catch (err) {
        return Err(err.message || String(err));
      }
    }
  };
};
export const mongodb = {
  connect: async (uriOrConfig) => {
    try {
      const client = __createAuraMongoWrapper(uriOrConfig);
      await client.ping();
      return Ok(client);
    } catch (err) {
      return Err(err.message || String(err));
    }
  },
  createClient: (config) => __createAuraMongoWrapper(config),
  open: (uri) => __createAuraMongoWrapper(uri),
  db: (name) => __createAuraMongoWrapper().db(name)
};
export const mongo = mongodb;

// --- Aura Standard Redis Key-Value & Cache Driver ---
const __createAuraRedisWrapper = (driverOrConfig) => {
  let redisPkg = null;
  let clientInstance = null;
  const getDriver = async () => {
    if (!redisPkg) {
      try {
        redisPkg = await __aura_import('ioredis');
      } catch (err) {
        try {
          redisPkg = await __aura_import('redis');
        } catch (err2) {
          throw new Error('Aura Redis runtime requires "ioredis" or "redis" package. Run: npm install ioredis');
        }
      }
    }
    return redisPkg;
  };
  const getClient = async () => {
    if (!clientInstance) {
      const drv = await getDriver();
      const RedisClass = drv.Redis || drv.default?.Redis || drv.default || drv.createClient;
      if (typeof RedisClass === 'function' && RedisClass.prototype) {
        if (typeof driverOrConfig === 'string') {
          clientInstance = new RedisClass(driverOrConfig);
        } else if (driverOrConfig && typeof driverOrConfig === 'object') {
          clientInstance = new RedisClass(driverOrConfig);
        } else {
          clientInstance = new RedisClass();
        }
      } else if (typeof drv.createClient === 'function') {
        const conf = typeof driverOrConfig === 'string' ? { url: driverOrConfig } : (driverOrConfig || {});
        clientInstance = drv.createClient(conf);
        if (clientInstance.connect) await clientInstance.connect();
      }
    }
    return clientInstance;
  };
  return {
    get: async (key) => {
      try {
        const client = await getClient();
        const val = await client.get(String(key));
        return Ok(val !== null && val !== undefined ? Some(String(val)) : None);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    set: async (key, val, ttlSeconds) => {
      try {
        const client = await getClient();
        const strVal = typeof val === 'object' ? JSON.stringify(val) : String(val);
        if (ttlSeconds && typeof ttlSeconds === 'number' && ttlSeconds > 0) {
          await client.set(String(key), strVal, 'EX', ttlSeconds);
        } else {
          await client.set(String(key), strVal);
        }
        return Ok(true);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    del: async (keyOrKeys) => {
      try {
        const client = await getClient();
        const count = Array.isArray(keyOrKeys) ? await client.del(...keyOrKeys) : await client.del(String(keyOrKeys));
        return Ok(typeof count === 'number' ? count : 1);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    exists: async (key) => {
      try {
        const client = await getClient();
        const count = await client.exists(String(key));
        return Ok(count > 0);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    incr: async (key) => {
      try {
        const client = await getClient();
        const val = await client.incr(String(key));
        return Ok(val);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    decr: async (key) => {
      try {
        const client = await getClient();
        const val = await client.decr(String(key));
        return Ok(val);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    expire: async (key, seconds) => {
      try {
        const client = await getClient();
        const res = await client.expire(String(key), seconds);
        return Ok(res === 1 || res === true);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    ttl: async (key) => {
      try {
        const client = await getClient();
        const t = await client.ttl(String(key));
        return Ok(t);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    keys: async (pattern = '*') => {
      try {
        const client = await getClient();
        const k = await client.keys(pattern);
        return Ok(Array.isArray(k) ? k : []);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    hget: async (key, field) => {
      try {
        const client = await getClient();
        const val = await client.hget(String(key), String(field));
        return Ok(val !== null && val !== undefined ? Some(String(val)) : None);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    hset: async (key, field, val) => {
      try {
        const client = await getClient();
        const strVal = typeof val === 'object' ? JSON.stringify(val) : String(val);
        const res = await client.hset(String(key), String(field), strVal);
        return Ok(typeof res === 'number' ? res : 1);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    hgetall: async (key) => {
      try {
        const client = await getClient();
        const map = await client.hgetall(String(key));
        return Ok(map || {});
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    hdel: async (key, field) => {
      try {
        const client = await getClient();
        const count = await client.hdel(String(key), String(field));
        return Ok(typeof count === 'number' ? count : 1);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    ping: async () => {
      try {
        const client = await getClient();
        const res = await client.ping();
        return Ok(typeof res === 'string' ? res : 'PONG');
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    flushall: async () => {
      try {
        const client = await getClient();
        await client.flushall();
        return Ok(true);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    close: async () => {
      try {
        if (clientInstance) {
          if (clientInstance.quit) await clientInstance.quit();
          else if (clientInstance.disconnect) clientInstance.disconnect();
        }
        return Ok(undefined);
      } catch (err) {
        return Err(err.message || String(err));
      }
    },
    quit: async () => {
      try {
        if (clientInstance) {
          if (clientInstance.quit) await clientInstance.quit();
          else if (clientInstance.disconnect) clientInstance.disconnect();
        }
        return Ok(undefined);
      } catch (err) {
        return Err(err.message || String(err));
      }
    }
  };
};
export const redis = {
  createClient: (config) => __createAuraRedisWrapper(config),
  open: (uri) => __createAuraRedisWrapper(uri),
  connect: async (uriOrConfig) => {
    try {
      const client = __createAuraRedisWrapper(uriOrConfig);
      await client.ping();
      return Ok(client);
    } catch (err) {
      return Err(err.message || String(err));
    }
  }
};

// --- Aura User Program Definitions ---
const ordersMutex = Mutex.new();
let ordersDb = [({ id: "ord-101", customer: ({ name: "Sofia Vergara", email: "sofia@correo.dev", address: "Av. Providencia 1234, Santiago" }), items: [({ productId: "prod-1", title: "Microservicios en Go y Aura", quantity: 2, unitPrice: 35.5 }), ({ productId: "prod-2", title: "Teclado Mecánico RGB", quantity: 1, unitPrice: 120 })], subtotal: 191, taxAmount: 36.29, total: 227.29, status: "PAID", createdAt: "2026-09-10T14:30:00Z" })];
const fulfillmentQueue = Channel.make(100);
spawn(async () => {
  println("⚡ [Fulfillment-Worker] Fiber de despacho en segundo plano iniciado.");
  while (true) { const ordOpt = (await fulfillmentQueue.recv()); (await (async (_m) => {
  if (_m && _m.$ === "Some") { const ord = _m._0;  return (await (async () => {
  println(`📦 [Fulfillment] Procesando despacho para orden #${ord.id}...`);
  (await sleep(50));
  return println(`✓ [Fulfillment] Orden #${ord.id} lista para despacho a ${ord.customer.address}.`);
})()); }
  else if (_m && _m.$ === "None") {  return undefined; }
  throw new Error("Non-exhaustive pattern match");
})(ordOpt)); }
});
const mux = http.newServeMux();
mux.use(((req, res, next) => ((() => {
  println(`[Orders-API] ${req.method} ${req.url}`);
  res.setHeader("X-Service", "Orders-Microservice");
  res.setHeader("X-Runtime", "Aura-Golang-Engine");
  return next();
})())));
mux.get("/api/health", ((req, res) => ((() => {
  return http.json(res, http.StatusOK, ({ service: "Orders Microservice", status: "HEALTHY", uptimeSeconds: process.uptime(), hostname: os.hostname(), serverTime: time.now() }));
})())));
mux.get("/api/orders", ((req, res) => ((() => {
  const __aura_defers = [];
  let __aura_panic_err = null;
  try {
  const statusFilter = http.query(req, "status");
  const customerFilter = http.query(req, "email");
  ordersMutex.lock();
  __aura_defers.push(() => { ordersMutex.unlock(); });
  const filtered = filter(ordersDb, ((o) => ((() => {
  const matchStatus = ((statusFilter === "") || (o.status === statusFilter));
  const matchEmail = ((customerFilter === "") || o.customer.email.toLowerCase().includes(customerFilter.toLowerCase()));
  return (matchStatus && matchEmail);
})())));
  return http.json(res, http.StatusOK, ({ count: filtered.length, orders: filtered }));
  } catch (__e) {
    __aura_panic_err = __e;
    __current_panic = (__e && __e.isPanic) ? __e.value : __e;
  } finally {
    for (let __i = __aura_defers.length - 1; __i >= 0; __i--) { __aura_defers[__i](); }
    if (__aura_panic_err !== null && __current_panic !== null) { throw __aura_panic_err; }
  }
})())));
mux.get("/api/orders/:id", ((req, res) => ((() => {
  const __aura_defers = [];
  let __aura_panic_err = null;
  try {
  const orderId = http.pathValue(req, "id");
  ordersMutex.lock();
  __aura_defers.push(() => { ordersMutex.unlock(); });
  const matched = filter(ordersDb, ((o) => (o.id === orderId)));
  if ((matched.length === 0)) { http.error(res, `Orden '${orderId}' no encontrada`, http.StatusNotFound); return undefined; }
  return http.json(res, http.StatusOK, matched[0]);
  } catch (__e) {
    __aura_panic_err = __e;
    __current_panic = (__e && __e.isPanic) ? __e.value : __e;
  } finally {
    for (let __i = __aura_defers.length - 1; __i >= 0; __i--) { __aura_defers[__i](); }
    if (__aura_panic_err !== null && __current_panic !== null) { throw __aura_panic_err; }
  }
})())));
mux.post("/api/orders", (async (req, res) => (await (async () => {
  const parseRes = (await http.parseJson(req));
  return (await (async (_m) => {
  if (_m && _m.$ === "Ok") { const body = (_m.value !== undefined ? _m.value : _m._0);  return (await (async () => {
  if (((body.customer === null) || (body.items === null))) { http.error(res, "Faltan campos obligatorios: 'customer' e 'items'", http.StatusBadRequest); return undefined; }
  const customer = ({ name: ((body.customer.name !== "") ? body.customer.name : "Anónimo"), email: ((body.customer.email !== "") ? body.customer.email : "sin-correo@aura.dev"), address: ((body.customer.address !== "") ? body.customer.address : "Retiro en tienda") });
  const rawItems = body.items;
  let subtotal = 0;
  let validatedItems = [];
  let i = 0;
  while ((i < rawItems.length)) { const it = rawItems[i]; const qty = ((it.quantity > 0) ? it.quantity : 1); const price = ((it.unitPrice > 0) ? it.unitPrice : 10); subtotal = (subtotal + (price * parseFloat(`${qty}`))); validatedItems.push(({ productId: ((it.productId !== "") ? it.productId : `prod-${(i + 1)}`), title: ((it.title !== "") ? it.title : "Artículo sin nombre"), quantity: qty, unitPrice: price })); i = (i + 1); }
  const taxRate = 0.19;
  const tax = (subtotal * taxRate);
  const grandTotal = (subtotal + tax);
  ordersMutex.lock();
  const newId = `ord-${(ordersDb.length + 101)}`;
  const newOrder = ({ id: newId, customer: customer, items: validatedItems, subtotal: subtotal, taxAmount: tax, total: grandTotal, status: "CONFIRMED", createdAt: `${time.now()}` });
  ordersDb.push(newOrder);
  ordersMutex.unlock();
  (await fulfillmentQueue.send(newOrder));
  return http.json(res, http.StatusCreated, ({ success: true, message: `Orden #${newId} creada con éxito`, order: newOrder }));
})()); }
  else if (_m && _m.$ === "Err") { const err = (_m.error !== undefined ? _m.error : _m._0);  return ((() => {
  return http.error(res, `Payload JSON inválido: ${err}`, http.StatusBadRequest);
})()); }
  throw new Error("Non-exhaustive pattern match");
})(parseRes));
})())));
mux.put("/api/orders/:id/cancel", ((req, res) => ((() => {
  const __aura_defers = [];
  let __aura_panic_err = null;
  try {
  const orderId = http.pathValue(req, "id");
  ordersMutex.lock();
  __aura_defers.push(() => { ordersMutex.unlock(); });
  let found = false;
  let i = 0;
  while ((i < ordersDb.length)) { if ((ordersDb[i].id === orderId)) { ordersDb[i].status = "CANCELLED"; found = true; break; } i = (i + 1); }
  if ((!found)) { http.error(res, `No se encontró la orden '${orderId}' para cancelar`, http.StatusNotFound); return undefined; }
  return http.json(res, http.StatusOK, ({ success: true, message: `Orden '${orderId}' ha sido cancelada exitosamente` }));
  } catch (__e) {
    __aura_panic_err = __e;
    __current_panic = (__e && __e.isPanic) ? __e.value : __e;
  } finally {
    for (let __i = __aura_defers.length - 1; __i >= 0; __i--) { __aura_defers[__i](); }
    if (__aura_panic_err !== null && __current_panic !== null) { throw __aura_panic_err; }
  }
})())));
mux.get("/api/orders/metrics", ((req, res) => ((() => {
  const __aura_defers = [];
  let __aura_panic_err = null;
  try {
  ordersMutex.lock();
  __aura_defers.push(() => { ordersMutex.unlock(); });
  let revenue = 0;
  let completedCount = 0;
  let i = 0;
  while ((i < ordersDb.length)) { const ord = ordersDb[i]; if ((ord.status !== "CANCELLED")) { revenue = (revenue + ord.total); } if (((ord.status === "PAID") || (ord.status === "CONFIRMED"))) { completedCount = (completedCount + 1); } i = (i + 1); }
  const metrics = ({ totalOrders: ordersDb.length, completedOrders: completedCount, totalRevenue: revenue, currency: "USD" });
  return http.json(res, http.StatusOK, metrics);
  } catch (__e) {
    __aura_panic_err = __e;
    __current_panic = (__e && __e.isPanic) ? __e.value : __e;
  } finally {
    for (let __i = __aura_defers.length - 1; __i >= 0; __i--) { __aura_defers[__i](); }
    if (__aura_panic_err !== null && __current_panic !== null) { throw __aura_panic_err; }
  }
})())));
const port = ((os.env("PORT") !== "") ? os.env("PORT") : "8081");
println(`🚀 Microservicio de Órdenes iniciado en http://localhost:${port}`);
mux.listenAndServe(`:${port}`);

//# sourceMappingURL=/Users/mavro/Projects/aura-lang/.aura/debug/orders_service.mjs.map
