[package]
name = "aura-lang"
version = "0.1.0"
edition = "2024"
license = "MIT"
default-run = "aurac"

[workspace]
members = [
    ".",
    "crates/aura-runtime",
]

[dependencies]
aura-runtime = { path = "crates/aura-runtime" }
cranelift-codegen = { version = "0.135.0", features = ["all-arch"] }
cranelift-frontend = "0.135.0"
cranelift-module = "0.135.0"
cranelift-object = "0.135.0"
target-lexicon = "0.13"
object = "0.36"

[[bin]]
name = "aurac"
path = "src/main.rs"

[[bin]]
name = "aurafmt"
path = "src/bin/aurafmt.rs"

[[bin]]
name = "auratest"
path = "src/bin/auratest.rs"

[[bin]]
name = "auralsp"
path = "src/bin/auralsp.rs"

[[bin]]
name = "auramod"
path = "src/bin/auramod.rs"

[[bin]]
name = "aurapkg"
path = "src/bin/aurapkg.rs"


