// Generated by Aura Self-Hosted Compiler (Target: ES6 / Node.js)
// --- Aura Runtime Primitives ---
export const None = Object.freeze({ $: "None" });
export const Some = (val) => Object.freeze({ $: "Some", _0: val });
export const Ok = (val) => Object.freeze({ $: "Ok", value: val });
export const Err = (err) => Object.freeze({ $: "Err", error: err });
export const __aura_unwrap = (v) => {
  if (v && typeof v === "object") {
    if (v.$ === "Err" || v.$ === "None") throw { __aura_early_return: true, value: v };
    if (v.$ === "Some") return v._0;
    if (v.$ === "Ok") return v.value;
  }
  return v;
};
export const println = console.log;
export const print = (msg) => process.stdout.write(String(msg));

function add(a, b) {
  try {
    return (a + b);
  } catch (_e) {
    if (_e && _e.__aura_early_return) return _e.value;
    throw _e;
  }
}

export function greet(name) {
  try {
    const msg = `Hello ${name} from Self-Hosted Aura Compiler!`;
    return msg;
  } catch (_e) {
    if (_e && _e.__aura_early_return) return _e.value;
    throw _e;
  }
}

export function computeSum(n) {
  try {
    let total = 0;
    let i = 1;
    ((() => { while ((i <= n)) { (() => {
  total = (total + i);
  i = (i + 1);
})(); } })());
    return total;
  } catch (_e) {
    if (_e && _e.__aura_early_return) return _e.value;
    throw _e;
  }
}

println(greet("Developer"));
println(`Sum of 1..100: ${computeSum(100)}`);